### ISSUE TITLE
jstl and taglib is missing

### ISSUE THREAD

**Issue by xiaoyuzhzh** [lhazlewood/apache-shiro-tutorial-webapp#2]
If you forgot to add the dependency of jstl and taglib?

**Comment by bdemers** [comment]
I know this is an old issue, but:
Depending on your app server you may need to handle loading of deps differently.
This example configures jetty to be run via `mvn jetty:run`

**Comment by qwgrsftewg** [comment]
if you use tomcat, you may should check this out: [https://www.timeglobal.cn/programming/q_7488/how-to-install-jstl-the-absolute-uri-http-java-sun-com-jstl-core-cannot-be-r/](https://www.timeglobal.cn/programming/q_7488/how-to-install-jstl-the-absolute-uri-http-java-sun-com-jstl-core-cannot-be-r/)
I'm using apache tomcat 7.0.92, and this dependency works for me:
```
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>jakarta.servlet.jsp.jstl</artifactId>
    <version>1.2.6</version>
</dependency>
