### ISSUE TITLE
Without Stormpath?

### ISSUE THREAD

**Issue by aadrian** [lhazlewood/apache-shiro-tutorial-webapp#8]
Hi,

Is it possible to use the Shiro Tutorial and the corresponding example without Stormpath?

Thank you.

**Comment by bdemers** [comment]
Absolutely, go take a look at some of the other example applications:
https://github.com/apache/shiro/tree/1.3.x/samples/web/

The realm is very pluggable (you could use a database, LDAP, crowd, etc)
